apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: geonews
  

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: ashish00234/geonews-frontend:latest
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: geonews
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0b8fd660d1a2e05c2,subnet-02d6e2aa1fff804a6,subnet-0e67a36d43cb483eb

spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80