apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: campusops
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0b8fd660d1a2e05c2,subnet-02d6e2aa1fff804a6,subnet-0e67a36d43cb483eb
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer