apiVersion: v1
kind: Secret
metadata:
  name: campusops-secret
  namespace: campusops
type: Opaque
stringData:
  MONGO_URI: mongodb://bhandariashish367_db_user:Ashish4570073@ac-leknutc-shard-00-00.kquyegz.mongodb.net:27017,ac-leknutc-shard-00-01.kquyegz.mongodb.net:27017,ac-leknutc-shard-00-02.kquyegz.mongodb.net:27017/campusops?ssl=true&replicaSet=atlas-3x30v3-shard-0&authSource=admin&appName=Cluster0